version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - ./backend/database:/var/www/database
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: 
      - "sh"
      - "-c"
      - "/usr/local/bin/init.sh && php artisan serve --host=0.0.0.0 --port=8000"


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nebula
      POSTGRES_USER: nebula_user
      POSTGRES_PASSWORD: nebula_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
