import { Navigate } from "react-router-dom";

import { pageRoute } from "../Routes/routeHelpers";
import type { AppRoute, LazyPageLoader } from "../Routes/routeTypes";
import { rootAdminOnly } from "../Routes/routeTypes";

const devToolboxPath = (path: string) => `/panel/dev${path === "/" ? "" : path}`;

const asDevToolboxRoute = (route: AppRoute): AppRoute => ({
  ...route,
  path: devToolboxPath(route.path),
  allowedRoles: rootAdminOnly,
});

const toolboxRoute = (path: string, load: LazyPageLoader): AppRoute => pageRoute(path, load);

const rootAdminToolboxSourceRoutes: AppRoute[] = [
  toolboxRoute("/dashboard-analytics", () => import("../pages/DashboardAnalytics")),
  toolboxRoute("/dashboard-crm", () => import("../pages/DashboardCrm")),
  toolboxRoute("/dashboard", () => import("../pages/DashboardEcommerce")),
  toolboxRoute("/index", () => import("../pages/DashboardEcommerce")),
  toolboxRoute("/dashboard-crypto", () => import("../pages/DashboardCrypto")),
  toolboxRoute("/dashboard-projects", () => import("../pages/DashboardProject")),
  toolboxRoute("/dashboard-nft", () => import("../pages/DashboardNFT")),
  toolboxRoute("/dashboard-job", () => import("../pages/DashboardJob")),
  toolboxRoute("/dashboard-blog", () => import("../pages/DashboardBlog")),

  // apps
  toolboxRoute("/apps-calendar", () => import("../pages/Calendar")),
  toolboxRoute("/apps-calendar-month-grid", () => import("../pages/Calendar/monthGrid")),
  toolboxRoute("/apps-ecommerce-products", () => import("../pages/Ecommerce/EcommerceProducts")),
  toolboxRoute("/apps-ecommerce-product-details", () => import("../pages/Ecommerce/EcommerceProducts/EcommerceProductDetail")),
  toolboxRoute("/apps-ecommerce-add-product", () => import("../pages/Ecommerce/EcommerceProducts/EcommerceAddProduct")),
  toolboxRoute("/apps-ecommerce-orders", () => import("../pages/Ecommerce/EcommerceOrders")),
  toolboxRoute("/apps-ecommerce-order-details", () => import("../pages/Ecommerce/EcommerceOrders/EcommerceOrderDetail")),
  toolboxRoute("/apps-ecommerce-customers", () => import("../pages/Ecommerce/EcommerceCustomers")),
  toolboxRoute("/apps-ecommerce-cart", () => import("../pages/Ecommerce/EcommerceCart")),
  toolboxRoute("/apps-ecommerce-checkout", () => import("../pages/Ecommerce/EcommerceCheckout")),
  toolboxRoute("/apps-ecommerce-sellers", () => import("../pages/Ecommerce/EcommerceSellers")),
  toolboxRoute("/apps-ecommerce-seller-details", () => import("../pages/Ecommerce/EcommerceSellers/EcommerceSellerDetail")),
  toolboxRoute("/apps-file-manager", () => import("../pages/FileManager")),
  toolboxRoute("/apps-todo", () => import("../pages/ToDo")),
  toolboxRoute("/apps-chat", () => import("../pages/Chat")),
  toolboxRoute("/apps-mailbox", () => import("../pages/EmailInbox")),
  toolboxRoute("/apps-email-basic", () => import("../pages/Email/EmailTemplates/BasicAction")),
  toolboxRoute("/apps-email-ecommerce", () => import("../pages/Email/EmailTemplates/EcommerceAction")),
  toolboxRoute("/apps-projects-list", () => import("../pages/Projects/ProjectList")),
  toolboxRoute("/apps-projects-overview", () => import("../pages/Projects/ProjectOverview")),
  toolboxRoute("/apps-projects-create", () => import("../pages/Projects/CreateProject")),
  toolboxRoute("/apps-tasks-kanban", () => import("../pages/Tasks/KanbanBoard")),
  toolboxRoute("/apps-tasks-list-view", () => import("../pages/Tasks/TaskList")),
  toolboxRoute("/apps-tasks-details", () => import("../pages/Tasks/TaskDetails")),
  toolboxRoute("/apps-crm-contacts", () => import("../pages/Crm/CrmContacts")),
  toolboxRoute("/apps-crm-companies", () => import("../pages/Crm/CrmCompanies")),
  toolboxRoute("/apps-crm-deals", () => import("../pages/Crm/CrmDeals")),
  toolboxRoute("/apps-crm-leads", () => import("../pages/Crm/CrmLeads")),
  toolboxRoute("/apps-invoices-list", () => import("../pages/Invoices/InvoiceList")),
  toolboxRoute("/apps-invoices-details", () => import("../pages/Invoices/InvoiceDetails")),
  toolboxRoute("/apps-invoices-create", () => import("../pages/Invoices/InvoiceCreate")),
  toolboxRoute("/apps-tickets-list", () => import("../pages/SupportTickets/ListView")),
  toolboxRoute("/apps-tickets-details", () => import("../pages/SupportTickets/TicketsDetails")),
  toolboxRoute("/apps-crypto-transactions", () => import("../pages/Crypto/Transactions")),
  toolboxRoute("/apps-crypto-buy-sell", () => import("../pages/Crypto/BuySell")),
  toolboxRoute("/apps-crypto-orders", () => import("../pages/Crypto/CryptoOrder")),
  toolboxRoute("/apps-crypto-wallet", () => import("../pages/Crypto/MyWallet")),
  toolboxRoute("/apps-crypto-ico", () => import("../pages/Crypto/ICOList")),
  toolboxRoute("/apps-crypto-kyc", () => import("../pages/Crypto/KYCVerification")),
  toolboxRoute("/apps-nft-marketplace", () => import("../pages/NFTMarketplace/Marketplace")),
  toolboxRoute("/apps-nft-collections", () => import("../pages/NFTMarketplace/Collections")),
  toolboxRoute("/apps-nft-create", () => import("../pages/NFTMarketplace/CreateNFT")),
  toolboxRoute("/apps-nft-creators", () => import("../pages/NFTMarketplace/Creators")),
  toolboxRoute("/apps-nft-explore", () => import("../pages/NFTMarketplace/ExploreNow")),
  toolboxRoute("/apps-nft-item-details", () => import("../pages/NFTMarketplace/Itemdetails")),
  toolboxRoute("/apps-nft-auction", () => import("../pages/NFTMarketplace/LiveAuction")),
  toolboxRoute("/apps-nft-ranking", () => import("../pages/NFTMarketplace/Ranking")),
  toolboxRoute("/apps-nft-wallet", () => import("../pages/NFTMarketplace/WalletConnect")),

  // charts
  toolboxRoute("/charts-apex-line", () => import("../pages/Charts/ApexCharts/LineCharts")),
  toolboxRoute("/charts-apex-area", () => import("../pages/Charts/ApexCharts/AreaCharts")),
  toolboxRoute("/charts-apex-column", () => import("../pages/Charts/ApexCharts/ColumnCharts")),
  toolboxRoute("/charts-apex-bar", () => import("../pages/Charts/ApexCharts/BarCharts")),
  toolboxRoute("/charts-apex-mixed", () => import("../pages/Charts/ApexCharts/MixedCharts")),
  toolboxRoute("/charts-apex-timeline", () => import("../pages/Charts/ApexCharts/TimelineCharts")),
  toolboxRoute("/charts-apex-range-area", () => import("../pages/Charts/ApexCharts/RangeAreaCharts/Index")),
  toolboxRoute("/charts-apex-funnel", () => import("../pages/Charts/ApexCharts/FunnelCharts")),
  toolboxRoute("/charts-apex-candlestick", () => import("../pages/Charts/ApexCharts/CandlestickChart")),
  toolboxRoute("/charts-apex-boxplot", () => import("../pages/Charts/ApexCharts/BoxplotCharts")),
  toolboxRoute("/charts-apex-bubble", () => import("../pages/Charts/ApexCharts/BubbleChart")),
  toolboxRoute("/charts-apex-scatter", () => import("../pages/Charts/ApexCharts/ScatterCharts")),
  toolboxRoute("/charts-apex-heatmap", () => import("../pages/Charts/ApexCharts/HeatmapCharts")),
  toolboxRoute("/charts-apex-treemap", () => import("../pages/Charts/ApexCharts/TreemapCharts")),
  toolboxRoute("/charts-apex-pie", () => import("../pages/Charts/ApexCharts/PieCharts")),
  toolboxRoute("/charts-apex-radialbar", () => import("../pages/Charts/ApexCharts/RadialbarCharts")),
  toolboxRoute("/charts-apex-radar", () => import("../pages/Charts/ApexCharts/RadarCharts")),
  toolboxRoute("/charts-apex-polar", () => import("../pages/Charts/ApexCharts/PolarCharts")),
  toolboxRoute("/charts-apex-slope", () => import("../pages/Charts/ApexCharts/SlopeCharts")),
  toolboxRoute("/charts-chartjs", () => import("../pages/Charts/ChartsJs")),
  toolboxRoute("/charts-echarts", () => import("../pages/Charts/ECharts")),

  // Base UI
  toolboxRoute("/ui-alerts", () => import("../pages/BaseUi/UiAlerts/UiAlerts")),
  toolboxRoute("/ui-badges", () => import("../pages/BaseUi/UiBadges/UiBadges")),
  toolboxRoute("/ui-buttons", () => import("../pages/BaseUi/UiButtons/UiButtons")),
  toolboxRoute("/ui-colors", () => import("../pages/BaseUi/UiColors/UiColors")),
  toolboxRoute("/ui-cards", () => import("../pages/BaseUi/UiCards/UiCards")),
  toolboxRoute("/ui-carousel", () => import("../pages/BaseUi/UiCarousel/UiCarousel")),
  toolboxRoute("/ui-dropdowns", () => import("../pages/BaseUi/UiDropdowns/UiDropdowns")),
  toolboxRoute("/ui-grid", () => import("../pages/BaseUi/UiGrid/UiGrid")),
  toolboxRoute("/ui-images", () => import("../pages/BaseUi/UiImages/UiImages")),
  toolboxRoute("/ui-tabs", () => import("../pages/BaseUi/UiTabs/UiTabs")),
  toolboxRoute("/ui-accordions", () => import("../pages/BaseUi/UiAccordion&Collapse/UiAccordion&Collapse")),
  toolboxRoute("/ui-modals", () => import("../pages/BaseUi/UiModals/UiModals")),
  toolboxRoute("/ui-offcanvas", () => import("../pages/BaseUi/UiOffcanvas/UiOffcanvas")),
  toolboxRoute("/ui-placeholders", () => import("../pages/BaseUi/UiPlaceholders/UiPlaceholders")),
  toolboxRoute("/ui-progress", () => import("../pages/BaseUi/UiProgress/UiProgress")),
  toolboxRoute("/ui-notifications", () => import("../pages/BaseUi/UiNotifications/UiNotifications")),
  toolboxRoute("/ui-media", () => import("../pages/BaseUi/UiMediaobject/UiMediaobject")),
  toolboxRoute("/ui-embed-video", () => import("../pages/BaseUi/UiEmbedVideo/UiEmbedVideo")),
  toolboxRoute("/ui-typography", () => import("../pages/BaseUi/UiTypography/UiTypography")),
  toolboxRoute("/ui-lists", () => import("../pages/BaseUi/UiLists/UiLists")),
  toolboxRoute("/ui-links", () => import("../pages/BaseUi/UiLink/UiLink")),
  toolboxRoute("/ui-general", () => import("../pages/BaseUi/UiGeneral/UiGeneral")),
  toolboxRoute("/ui-ribbons", () => import("../pages/BaseUi/UiRibbons/UiRibbons")),
  toolboxRoute("/ui-utilities", () => import("../pages/BaseUi/UiUtilities/UiUtilities")),

  // Advanced UI
  toolboxRoute("/advance-ui-scrollbar", () => import("../pages/AdvanceUi/UiScrollbar/UiScrollbar")),
  toolboxRoute("/advance-ui-animation", () => import("../pages/AdvanceUi/UiAnimation/UiAnimation")),
  toolboxRoute("/advance-ui-swiper", () => import("../pages/AdvanceUi/UiSwiperSlider/UiSwiperSlider")),
  toolboxRoute("/advance-ui-ratings", () => import("../pages/AdvanceUi/UiRatings/UiRatings")),
  toolboxRoute("/advance-ui-highlight", () => import("../pages/AdvanceUi/UiHighlight/UiHighlight")),

  // Widgets, forms, tables, icons, maps, and pages
  toolboxRoute("/widgets", () => import("../pages/Widgets/Index")),
  toolboxRoute("/forms-elements", () => import("../pages/Forms/BasicElements/BasicElements")),
  toolboxRoute("/forms-select", () => import("../pages/Forms/FormSelect/FormSelect")),
  toolboxRoute("/forms-editors", () => import("../pages/Forms/FormEditor/FormEditor")),
  toolboxRoute("/forms-checkboxes-radios", () => import("../pages/Forms/CheckboxAndRadio/CheckBoxAndRadio")),
  toolboxRoute("/forms-masks", () => import("../pages/Forms/Masks/Masks")),
  toolboxRoute("/forms-file-uploads", () => import("../pages/Forms/FileUpload/FileUpload")),
  toolboxRoute("/forms-pickers", () => import("../pages/Forms/FormPickers/FormPickers")),
  toolboxRoute("/forms-range-sliders", () => import("../pages/Forms/FormRangeSlider/FormRangeSlider")),
  toolboxRoute("/forms-layouts", () => import("../pages/Forms/FormLayouts/Formlayouts")),
  toolboxRoute("/forms-validation", () => import("../pages/Forms/FormValidation/FormValidation")),
  toolboxRoute("/forms-wizard", () => import("../pages/Forms/FormWizard/FormWizard")),
  toolboxRoute("/forms-advanced", () => import("../pages/Forms/FormAdvanced/FormAdvanced")),
  toolboxRoute("/forms-select2", () => import("../pages/Forms/Select2/Select2")),
  toolboxRoute("/tables-basic", () => import("../pages/Tables/BasicTables/BasicTables")),
  toolboxRoute("/tables-react", () => import("../pages/Tables/ReactTables")),
  toolboxRoute("/icons-remix", () => import("../pages/Icons/RemixIcons/RemixIcons")),
  toolboxRoute("/icons-boxicons", () => import("../pages/Icons/BoxIcons/BoxIcons")),
  toolboxRoute("/icons-materialdesign", () => import("../pages/Icons/MaterialDesign/MaterialDesign")),
  toolboxRoute("/icons-feather", () => import("../pages/Icons/FeatherIcons/FeatherIcons")),
  toolboxRoute("/icons-lineawesome", () => import("../pages/Icons/LineAwesomeIcons/LineAwesomeIcons")),
  toolboxRoute("/icons-crypto", () => import("../pages/Icons/CryptoIcons/CryptoIcons")),
  toolboxRoute("/maps-google", () => import("../pages/Maps/GoogleMaps/GoogleMaps")),
  toolboxRoute("/pages-starter", () => import("../pages/Pages/Starter/Starter")),
  toolboxRoute("/pages-profile", () => import("../pages/Pages/Profile/SimplePage/SimplePage")),
  toolboxRoute("/pages-profile-settings", () => import("../pages/Pages/Profile/Settings/Settings")),
  toolboxRoute("/pages-team", () => import("../pages/Pages/Team/Team")),
  toolboxRoute("/pages-timeline", () => import("../pages/Pages/Timeline/Timeline")),
  toolboxRoute("/pages-faqs", () => import("../pages/Pages/Faqs/Faqs")),
  toolboxRoute("/pages-gallery", () => import("../pages/Pages/Gallery/Gallery")),
  toolboxRoute("/pages-pricing", () => import("../pages/Pages/Pricing/Pricing")),
  toolboxRoute("/pages-sitemap", () => import("../pages/Pages/SiteMap/SiteMap")),
  toolboxRoute("/pages-search-results", () => import("../pages/Pages/SearchResults/SearchResults")),
  toolboxRoute("/pages-blog-list", () => import("../pages/Pages/Blogs/ListView")),
  toolboxRoute("/pages-blog-grid", () => import("../pages/Pages/Blogs/GridView")),
  toolboxRoute("/pages-blog-overview", () => import("../pages/Pages/Blogs/Overview")),

  // Jobs
  toolboxRoute("/apps-job-statistics", () => import("../pages/Jobs/Statistics")),
  toolboxRoute("/apps-job-lists", () => import("../pages/Jobs/JobList/List")),
  toolboxRoute("/apps-job-grid-lists", () => import("../pages/Jobs/JobList/Grid")),
  toolboxRoute("/apps-job-details", () => import("../pages/Jobs/JobList/Overview")),
  toolboxRoute("/apps-job-candidate-lists", () => import("../pages/Jobs/CandidateList/ListView")),
  toolboxRoute("/apps-job-candidate-grid", () => import("../pages/Jobs/CandidateList/GridView")),
  toolboxRoute("/apps-job-application", () => import("../pages/Jobs/Application")),
  toolboxRoute("/apps-job-new", () => import("../pages/Jobs/NewJob")),
  toolboxRoute("/apps-job-companies-lists", () => import("../pages/Jobs/CompaniesList")),
  toolboxRoute("/apps-job-categories", () => import("../pages/Jobs/JobCategories")),
  toolboxRoute("/apps-api-key", () => import("../pages/APIKey")),
  toolboxRoute("/pages-privacy-policy", () => import("../pages/Pages/PrivacyPolicy")),
  toolboxRoute("/pages-terms-condition", () => import("../pages/Pages/TermsCondition")),
];

const publicRootAdminToolboxSourceRoutes: AppRoute[] = [
  toolboxRoute("/auth-signin-basic", () => import("../pages/AuthenticationInner/Login/BasicSignIn")),
  toolboxRoute("/auth-signin-cover", () => import("../pages/AuthenticationInner/Login/CoverSignIn")),
  toolboxRoute("/auth-signup-basic", () => import("../pages/AuthenticationInner/Register/BasicSignUp")),
  toolboxRoute("/auth-signup-cover", () => import("../pages/AuthenticationInner/Register/CoverSignUp")),
  toolboxRoute("/auth-pass-reset-basic", () => import("../pages/AuthenticationInner/PasswordReset/BasicPasswReset")),
  toolboxRoute("/auth-pass-reset-cover", () => import("../pages/AuthenticationInner/PasswordReset/CoverPasswReset")),
  toolboxRoute("/auth-lockscreen-basic", () => import("../pages/AuthenticationInner/LockScreen/BasicLockScr")),
  toolboxRoute("/auth-lockscreen-cover", () => import("../pages/AuthenticationInner/LockScreen/CoverLockScr")),
  toolboxRoute("/auth-logout-basic", () => import("../pages/AuthenticationInner/Logout/BasicLogout")),
  toolboxRoute("/auth-logout-cover", () => import("../pages/AuthenticationInner/Logout/CoverLogout")),
  toolboxRoute("/auth-success-msg-basic", () => import("../pages/AuthenticationInner/SuccessMessage/BasicSuccessMsg")),
  toolboxRoute("/auth-success-msg-cover", () => import("../pages/AuthenticationInner/SuccessMessage/CoverSuccessMsg")),
  toolboxRoute("/auth-twostep-basic", () => import("../pages/AuthenticationInner/TwoStepVerification/BasicTwosVerify")),
  toolboxRoute("/auth-twostep-cover", () => import("../pages/AuthenticationInner/TwoStepVerification/CoverTwosVerify")),
  toolboxRoute("/auth-404-basic", () => import("../pages/AuthenticationInner/Errors/Basic404")),
  toolboxRoute("/auth-404-cover", () => import("../pages/AuthenticationInner/Errors/Cover404")),
  toolboxRoute("/auth-404-alt", () => import("../pages/AuthenticationInner/Errors/Alt404")),
  toolboxRoute("/auth-500", () => import("../pages/AuthenticationInner/Errors/Error500")),
  toolboxRoute("/pages-maintenance", () => import("../pages/Pages/Maintenance/Maintenance")),
  toolboxRoute("/pages-coming-soon", () => import("../pages/Pages/ComingSoon/ComingSoon")),
  toolboxRoute("/landing", () => import("../pages/Landing/OnePage")),
  toolboxRoute("/nft-landing", () => import("../pages/Landing/NFTLanding")),
  toolboxRoute("/job-landing", () => import("../pages/Job_Landing/Job")),
  toolboxRoute("/auth-pass-change-basic", () => import("../pages/AuthenticationInner/PasswordCreate/BasicPasswCreate")),
  toolboxRoute("/auth-pass-change-cover", () => import("../pages/AuthenticationInner/PasswordCreate/CoverPasswCreate")),
  toolboxRoute("/auth-offline", () => import("../pages/AuthenticationInner/Errors/Offlinepage")),
];

export const rootAdminToolboxRoutes: AppRoute[] = [
  {
    path: "/panel/dev",
    component: <Navigate to="/panel/dev/dashboard-analytics" />,
    allowedRoles: rootAdminOnly,
  },
  ...rootAdminToolboxSourceRoutes.map(asDevToolboxRoute),
  ...publicRootAdminToolboxSourceRoutes.map(asDevToolboxRoute),
];
